CREATE USER someuser WITH PASSWORD 'some_password';
GRANT ALL ON SCHEMA public TO someuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO someuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO someuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO someuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO someuser;